services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-nanoid
    environment:
      POSTGRES_DB: nanoid_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./tests:/tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nanoid_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: